name: project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  jiffy: ^6.4.4
  http: ^1.6.0
  cached_network_image: ^3.2.0
  image_picker: ^1.2.1
  show_up_animation: ^2.0.0
  auto_animated: ^3.0.1
  flutter_polyline_points: ^3.1.0
  google_maps_flutter: ^2.1.5
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  firebase_messaging: ^16.1.2
  firebase_core: ^4.5.0
  flutter_local_notifications: ^21.0.0
  cloud_firestore: ^6.1.3
  sqflite: ^2.0.2
  shared_preferences: ^2.0.15
  path: ^1.8.0
  qr_flutter: ^4.0.0
  barcode_scan2: ^4.7.2
  grouped_list: ^6.0.0
  url_launcher: ^6.1.2
  dropdown_search: ^6.0.2
  badges: ^3.1.2
  flutter_svg: ^2.2.4
  font_awesome_flutter: ^11.0.0
  fluttericon: ^2.0.0
  dartz: ^0.10.1
  google_sign_in: ^7.2.0
  device_preview: ^1.3.1
  responsive_builder: ^0.7.1
  image_pickers: ^2.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^6.0.0

flutter:


  uses-material-design: true


  assets:
     - assets/images/acce.jpg
     - assets/images/forgot.png
     - assets/images/verifier.png
     - assets/images/home.jpg



  fonts:
     - family: Regular
       fonts:
           - asset: assets/fonts/Mulish-Regular.ttf
     - family: Bold
       fonts:
           - asset: assets/fonts/Mulish-bold.ttf